<#

.SYNOPSIS			Module Switcher panel for HOL vPods.

.DESCRIPTION	

.NOTES				
							Version 0.00 - 01 March 2016
 
.EXAMPLE			.\testPanel

.INPUTS				Provide scripts with names like "Module02.ps1" in the $ModuleSwitchDir

.OUTPUTS			Scripts are launched in their own PS console

#>

#$ModuleSwitchDir = 'C:\HOL\ModuleSwitcher'
$ModuleSwitchDir = 'E:\Temp\ModuleSwitcher'
if( Test-Path $ModuleSwitchDir ) {
	$ModuleScripts = Get-ChildItem -Path $ModuleSwitchDir -Filter 'Module*.ps1' | Sort
} else {
	Write-Host -ForegroundColor Red "ERROR - Unable to locate $ModuleSwitchDir"
	exit
}

$activeModule = 1

# Create a hashtable of Start buttons here
$StartButtons = @{}

## ideally, break out Start/Stop pairs here. plan for 8 (allows for modules 1-9)
## if we can activate groupBoxes based on having a pair of scripts, that would be good.

function DisablePrevious { 
	PARAM ( [int]$thisModule )
	PROCESS {
		if( $thisModule -gt $activeModule ) {
			for($i=$activeModule; $i -le $thisModule; $i++) {
				$buttonName = "Start$i"
				if( $StartButtons.ContainsKey($buttonName) ) {
					$StartButtons[$buttonName].Enabled = $false
				}
			}
			$activeModule = $thisModule
		} else {
			#how did we get here?
			$wshell = New-Object -ComObject Wscript.Shell
			$wshell.Popup("Attempting to go backwards!",0,"Oops!",0x1)
		}
	}
}

#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.4.0
# Generated On: 2/29/2016 2:23 PM
# Generated By: dbaer
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$moduleSwitcherForm = New-Object System.Windows.Forms.Form
$gbModule2 = New-Object System.Windows.Forms.GroupBox
$m2Start = New-Object System.Windows.Forms.Button
$m2Stop = New-Object System.Windows.Forms.Button
$StartButtons.add("Start2",$m2Start)
$gbModule3 = New-Object System.Windows.Forms.GroupBox
$m3Start = New-Object System.Windows.Forms.Button
$m3Stop = New-Object System.Windows.Forms.Button
$StartButtons.add("Start3",$m3Start)
$gbModule4 = New-Object System.Windows.Forms.GroupBox
$m4Start = New-Object System.Windows.Forms.Button
$m4Stop = New-Object System.Windows.Forms.Button
$StartButtons.add("Start4",$m4Start)

$progressBar1 = New-Object System.Windows.Forms.ProgressBar
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Event Script Blocks
#----------------------------------------------

#Example to display a dialog
#	$wshell = New-Object -ComObject Wscript.Shell
#	$wshell.Popup("Stop Module 4",0,"Cool!",0x1)


$m2Start_OnClick= 
{
	$ScriptPath = Join-Path $ModuleSwitchDir "Module2_Start.ps1"
	Start-Process powershell -ArgumentList "-command $ScriptPath"
	$progressBar1.Value = 20
	DisablePrevious 2
	$m2Start.Enabled = $false
}

$m2Stop_OnClick= 
{
	$ScriptPath = Join-Path $ModuleSwitchDir "Module2_Stop.ps1"
	Start-Process powershell -ArgumentList "-command $ScriptPath"
	$progressBar1.Value = 40
	$m2Start.Enabled = $false
	$m2Stop.Enabled = $false
}

$m3Start_OnClick= 
{
	$ScriptPath = Join-Path $ModuleSwitchDir "Module3_Start.ps1"
	Start-Process powershell -ArgumentList "-command $ScriptPath"
	$progressBar1.Value = 60
	DisablePrevious 3
}

$m3Stop_OnClick= 
{
	$ScriptPath = Join-Path $ModuleSwitchDir "Module3_Stop.ps1"
	Start-Process powershell -ArgumentList "-command $ScriptPath"
	$progressBar1.Value = 80
}

$m4Start_OnClick= 
{
	$ScriptPath = Join-Path $ModuleSwitchDir "Module4_Start.ps1"
	Start-Process powershell -ArgumentList "-command $ScriptPath"
	$progressBar1.Value = 90
	DisablePrevious 4
}

$m4Stop_OnClick= 
{
	$ScriptPath = Join-Path $ModuleSwitchDir "Module4_Stop.ps1"
	Start-Process powershell -ArgumentList "-command $ScriptPath"
	$progressBar1.Value = 100
}



$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$moduleSwitcherForm.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$moduleSwitcherForm.Text = "ModuleSwitcher Form"
$moduleSwitcherForm.Name = "moduleSwitcherForm"
$moduleSwitcherForm.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 450
$System_Drawing_Size.Height = 500
$moduleSwitcherForm.ClientSize = $System_Drawing_Size


########################################################################
### Module 2 Group Box

$gbModule2.Name = "gbModule2"

$gbModule2.Text = "Module 2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 180
$System_Drawing_Size.Height = 70
$gbModule2.Size = $System_Drawing_Size
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 10
$System_Drawing_Point.Y = 50
$gbModule2.Location = $System_Drawing_Point
$gbModule2.TabStop = $False
$gbModule2.TabIndex = 0
$gbModule2.DataBindings.DefaultDataSourceUpdateMode = 0

$moduleSwitcherForm.Controls.Add($gbModule2)
$m2Start.TabIndex = 1
$m2Start.Name = "m2Start"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 75
$System_Drawing_Size.Height = 25
$m2Start.Size = $System_Drawing_Size
$m2Start.UseVisualStyleBackColor = $True

$m2Start.Text = "Start"

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 5
$System_Drawing_Point.Y = 20
$m2Start.Location = $System_Drawing_Point
$m2Start.DataBindings.DefaultDataSourceUpdateMode = 0
$m2Start.add_Click($m2Start_OnClick)

$gbModule2.Controls.Add($m2Start)



$m2Stop.TabIndex = 2
$m2Stop.Name = "m2Stop"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 75
$System_Drawing_Size.Height = 25
$m2Stop.Size = $System_Drawing_Size
$m2Stop.UseVisualStyleBackColor = $True

$m2Stop.Text = "Stop"

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 100
$System_Drawing_Point.Y = 20
$m2Stop.Location = $System_Drawing_Point
$m2Stop.DataBindings.DefaultDataSourceUpdateMode = 0
$m2Stop.add_Click($m2Stop_OnClick)

$gbModule2.Controls.Add($m2Stop)


########################################################################
### Module 3 Group Box


$gbModule3.Name = "gbModule3"

$gbModule3.Text = "Module 3"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 180
$System_Drawing_Size.Height = 70
$gbModule3.Size = $System_Drawing_Size
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 10
$System_Drawing_Point.Y = 150
$gbModule3.Location = $System_Drawing_Point
$gbModule3.TabStop = $False
$gbModule3.TabIndex = 4
$gbModule3.DataBindings.DefaultDataSourceUpdateMode = 0

$moduleSwitcherForm.Controls.Add($gbModule3)
$m3Start.TabIndex = 5
$m3Start.Name = "m3Start"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 75
$System_Drawing_Size.Height = 25
$m3Start.Size = $System_Drawing_Size
$m3Start.UseVisualStyleBackColor = $True

$m3Start.Text = "Start"

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 5
$System_Drawing_Point.Y = 20
$m3Start.Location = $System_Drawing_Point
$m3Start.DataBindings.DefaultDataSourceUpdateMode = 0
$m3Start.add_Click($m3Start_OnClick)

$gbModule3.Controls.Add($m3Start)

$m3Stop.TabIndex = 6
$m3Stop.Name = "m3Stop"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 75
$System_Drawing_Size.Height = 25
$m3Stop.Size = $System_Drawing_Size
$m3Stop.UseVisualStyleBackColor = $True

$m3Stop.Text = "Stop"

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 100
$System_Drawing_Point.Y = 20
$m3Stop.Location = $System_Drawing_Point
$m3Stop.DataBindings.DefaultDataSourceUpdateMode = 0
$m3Stop.add_Click($m3Stop_OnClick)

$gbModule3.Controls.Add($m3Stop)


########################################################################
### Module 4 Group Box

$gbModule4.Name = "gbModule4"
$gbModule4.Text = "Module 4"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 180
$System_Drawing_Size.Height = 70
$gbModule4.Size = $System_Drawing_Size
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 10
$System_Drawing_Point.Y = 250
$gbModule4.Location = $System_Drawing_Point
$gbModule4.TabStop = $False
$gbModule4.TabIndex = 7
$gbModule4.DataBindings.DefaultDataSourceUpdateMode = 0


$m4Start.TabIndex = 8
$m4Start.Name = "m4Start"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 75
$System_Drawing_Size.Height = 25
$m4Start.Size = $System_Drawing_Size
$m4Start.UseVisualStyleBackColor = $True

$m4Start.Text = "Start"

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 5
$System_Drawing_Point.Y = 20
$m4Start.Location = $System_Drawing_Point
$m4Start.DataBindings.DefaultDataSourceUpdateMode = 0
$m4Start.add_Click($m4Start_OnClick)

$gbModule4.Controls.Add($m4Start)


$moduleSwitcherForm.Controls.Add($gbModule4)
$m4Stop.TabIndex = 9
$m4Stop.Name = "m4Stop"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 75
$System_Drawing_Size.Height = 25
$m4Stop.Size = $System_Drawing_Size
$m4Stop.UseVisualStyleBackColor = $True

$m4Stop.Text = "Stop"

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 100
$System_Drawing_Point.Y = 20
$m4Stop.Location = $System_Drawing_Point
$m4Stop.DataBindings.DefaultDataSourceUpdateMode = 0
$m4Stop.add_Click($m4Stop_OnClick)

$gbModule4.Controls.Add($m4Stop)


########################################################################


## Progress Bar @ Bottom

$progressBar1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 425
$System_Drawing_Size.Height = 25
$progressBar1.Size = $System_Drawing_Size
$progressBar1.TabIndex = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 10
$System_Drawing_Point.Y = 450
$progressBar1.Location = $System_Drawing_Point
$progressBar1.Name = "progressBar1"

$moduleSwitcherForm.Controls.Add($progressBar1)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $moduleSwitcherForm.WindowState
#Init the OnLoad event to correct the initial state of the form
$moduleSwitcherForm.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$moduleSwitcherForm.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
